# Generated by Django 4.1.1 on 2022-09-29 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyuseranswer',
            name='pub_date',
        ),
    ]
